// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CodespacesColumns holds the columns for the "codespaces" table.
	CodespacesColumns = []*schema.Column{
		{Name: "old", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "machine_type", Type: field.TypeString},
		{Name: "client_ip", Type: field.TypeString},
		{Name: "github_user_id", Type: field.TypeString},
		{Name: "github_codespace_id", Type: field.TypeString},
		{Name: "github_codespace_url", Type: field.TypeString},
	}
	// CodespacesTable holds the schema information for the "codespaces" table.
	CodespacesTable = &schema.Table{
		Name:       "codespaces",
		Columns:    CodespacesColumns,
		PrimaryKey: []*schema.Column{CodespacesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CodespacesTable,
	}
)

func init() {
}
