// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"primijenjena-informatika-dev/ent/codespace"
	"primijenjena-informatika-dev/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CodespaceDelete is the builder for deleting a Codespace entity.
type CodespaceDelete struct {
	config
	hooks    []Hook
	mutation *CodespaceMutation
}

// Where appends a list predicates to the CodespaceDelete builder.
func (cd *CodespaceDelete) Where(ps ...predicate.Codespace) *CodespaceDelete {
	cd.mutation.Where(ps...)
	return cd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cd *CodespaceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cd.sqlExec, cd.mutation, cd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cd *CodespaceDelete) ExecX(ctx context.Context) int {
	n, err := cd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cd *CodespaceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(codespace.Table, sqlgraph.NewFieldSpec(codespace.FieldID, field.TypeUUID))
	if ps := cd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cd.mutation.done = true
	return affected, err
}

// CodespaceDeleteOne is the builder for deleting a single Codespace entity.
type CodespaceDeleteOne struct {
	cd *CodespaceDelete
}

// Where appends a list predicates to the CodespaceDelete builder.
func (cdo *CodespaceDeleteOne) Where(ps ...predicate.Codespace) *CodespaceDeleteOne {
	cdo.cd.mutation.Where(ps...)
	return cdo
}

// Exec executes the deletion query.
func (cdo *CodespaceDeleteOne) Exec(ctx context.Context) error {
	n, err := cdo.cd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{codespace.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cdo *CodespaceDeleteOne) ExecX(ctx context.Context) {
	if err := cdo.Exec(ctx); err != nil {
		panic(err)
	}
}
